baseURL = 'https://new.riverlog.info/'
languageCode = 'en-us'
title = 'RiverLog'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
